POST https://projetonodejs-ni07.onrender.com/videos
Content-Type: application/json

{
    "title": "Video node",
    "description": "O primeiro vídeo",
    "duration": 180
}

###

GET  https://projetonodejs-ni07.onrender.com/videos?search=node

###

PUT  https://projetonodejs-ni07.onrender.com/videos/286147d2-1837-4982-9ae0-4f29af49fa91
Content-Type: application/json

{
    "title": "Video 02",
    "description": "O primeiro vídeo",
    "duration": 180
}


###
DELETE  https://projetonodejs-ni07.onrender.com/videos/286147d2-1837-4982-9ae0-4f29af49fa91
